package com.codepunk.hollarhype.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class ColorFamily(
    val color: Color,
    val onColor: Color,
    val colorContainer: Color,
    val onColorContainer: Color
)

@Immutable
data class FixedColorScheme(
    val primaryFixed: Color,
    val onPrimaryFixed: Color,
    val secondaryFixed: Color,
    val onSecondaryFixed: Color,
    val tertiaryFixed: Color,
    val onTertiaryFixed: Color,
    val quaternaryFixed: Color,
    val onQuaternaryFixed: Color,
    val primaryFixedDim: Color,
    val onPrimaryFixedDim: Color,
    val secondaryFixedDim: Color,
    val onSecondaryFixedDim: Color,
    val tertiaryFixedDim: Color,
    val onTertiaryFixedDim: Color,
    val quaternaryFixedDim: Color,
    val onQuaternaryFixedDim: Color
)

val HypeGreen = Color(0xFFB4F946)
val HypeBlue = Color(0xFF3BA4FF)
val HypeOrange = Color(0xFFFFB155)
val HypeMagenta = Color(0xFFFF3BFB)
val HypeNeutral = Color(0xFF151925)
val HypeNeutralVariant = Color(0xFFF5F5F5)

val primaryLight = Color(0xFF456900)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB8FD4A)
val onPrimaryContainerLight = Color(0xFF365400)
val secondaryLight = Color(0xFF0061A2)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF5FAFFF)
val onSecondaryContainerLight = Color(0xFF00213C)
val tertiaryLight = Color(0xFF885200)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFBC71)
val onTertiaryContainerLight = Color(0xFF533000)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5F5F5)
val onBackgroundLight = Color(0xFF151925)
val surfaceLight = Color(0xFFFCF8F9)
val onSurfaceLight = Color(0xFF1C1B1C)
val surfaceVariantLight = Color(0xFFE0E3E3)
val onSurfaceVariantLight = Color(0xFF444748)
val outlineLight = Color(0xFF747878)
val outlineVariantLight = Color(0xFFC4C7C7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313031)
val inverseOnSurfaceLight = Color(0xFFF3F0F1)
val inversePrimaryLight = Color(0xFF97DA25)
val surfaceDimLight = Color(0xFFDCD9DA)
val surfaceBrightLight = Color(0xFFFCF8F9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F4)
val surfaceContainerLight = Color(0xFFF0EDEE)
val surfaceContainerHighLight = Color(0xFFEBE7E8)
val surfaceContainerHighestLight = Color(0xFFE5E2E3)

val primaryLightMediumContrast = Color(0xFF304A00)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF558100)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF004575)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF0078C6)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF623A00)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFA56609)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF5F5F5)
val onBackgroundLightMediumContrast = Color(0xFF151925)
val surfaceLightMediumContrast = Color(0xFFFCF8F9)
val onSurfaceLightMediumContrast = Color(0xFF1C1B1C)
val surfaceVariantLightMediumContrast = Color(0xFFE0E3E3)
val onSurfaceVariantLightMediumContrast = Color(0xFF404344)
val outlineLightMediumContrast = Color(0xFF5C6060)
val outlineVariantLightMediumContrast = Color(0xFF787B7C)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF313031)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF3F0F1)
val inversePrimaryLightMediumContrast = Color(0xFF97DA25)
val surfaceDimLightMediumContrast = Color(0xFFDCD9DA)
val surfaceBrightLightMediumContrast = Color(0xFFFCF8F9)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF6F3F4)
val surfaceContainerLightMediumContrast = Color(0xFFF0EDEE)
val surfaceContainerHighLightMediumContrast = Color(0xFFEBE7E8)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE5E2E3)

val primaryLightHighContrast = Color(0xFF172700)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF304A00)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF002440)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF004575)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF351D00)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF623A00)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF5F5F5)
val onBackgroundLightHighContrast = Color(0xFF151925)
val surfaceLightHighContrast = Color(0xFFFCF8F9)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE0E3E3)
val onSurfaceVariantLightHighContrast = Color(0xFF212525)
val outlineLightHighContrast = Color(0xFF404344)
val outlineVariantLightHighContrast = Color(0xFF404344)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF313031)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFC1FF63)
val surfaceDimLightHighContrast = Color(0xFFDCD9DA)
val surfaceBrightLightHighContrast = Color(0xFFFCF8F9)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF6F3F4)
val surfaceContainerLightHighContrast = Color(0xFFF0EDEE)
val surfaceContainerHighLightHighContrast = Color(0xFFEBE7E8)
val surfaceContainerHighestLightHighContrast = Color(0xFFE5E2E3)

val primaryDark = Color(0xFFFFFFFF)
val onPrimaryDark = Color(0xFF223600)
val primaryContainerDark = Color(0xFFA5E835)
val onPrimaryContainerDark = Color(0xFF2D4700)
val secondaryDark = Color(0xFF9DCAFF)
val onSecondaryDark = Color(0xFF003257)
val secondaryContainerDark = Color(0xFF2F9CF7)
val onSecondaryContainerDark = Color(0xFF00040C)
val tertiaryDark = Color(0xFFFFE0C3)
val onTertiaryDark = Color(0xFF482900)
val tertiaryContainerDark = Color(0xFFF9AC50)
val onTertiaryContainerDark = Color(0xFF462700)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF151925)
val onBackgroundDark = Color(0xFFF5F5F5)
val surfaceDark = Color(0xFF131314)
val onSurfaceDark = Color(0xFFE5E2E3)
val surfaceVariantDark = Color(0xFF444748)
val onSurfaceVariantDark = Color(0xFFC4C7C7)
val outlineDark = Color(0xFF8E9192)
val outlineVariantDark = Color(0xFF444748)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E3)
val inverseOnSurfaceDark = Color(0xFF313031)
val inversePrimaryDark = Color(0xFF456900)
val surfaceDimDark = Color(0xFF131314)
val surfaceBrightDark = Color(0xFF3A393A)
val surfaceContainerLowestDark = Color(0xFF0E0E0F)
val surfaceContainerLowDark = Color(0xFF1C1B1C)
val surfaceContainerDark = Color(0xFF201F20)
val surfaceContainerHighDark = Color(0xFF2A2A2B)
val surfaceContainerHighestDark = Color(0xFF353435)

val primaryDarkMediumContrast = Color(0xFFFFFFFF)
val onPrimaryDarkMediumContrast = Color(0xFF223600)
val primaryContainerDarkMediumContrast = Color(0xFFA5E835)
val onPrimaryContainerDarkMediumContrast = Color(0xFF152400)
val secondaryDarkMediumContrast = Color(0xFFA5CEFF)
val onSecondaryDarkMediumContrast = Color(0xFF00172D)
val secondaryContainerDarkMediumContrast = Color(0xFF2F9CF7)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFE0C3)
val onTertiaryDarkMediumContrast = Color(0xFF422500)
val tertiaryContainerDarkMediumContrast = Color(0xFFF9AC50)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF151925)
val onBackgroundDarkMediumContrast = Color(0xFFF5F5F5)
val surfaceDarkMediumContrast = Color(0xFF131314)
val onSurfaceDarkMediumContrast = Color(0xFFFDFAFB)
val surfaceVariantDarkMediumContrast = Color(0xFF444748)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC8CBCC)
val outlineDarkMediumContrast = Color(0xFFA0A3A4)
val outlineVariantDarkMediumContrast = Color(0xFF808484)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE5E2E3)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2A2B)
val inversePrimaryDarkMediumContrast = Color(0xFF335000)
val surfaceDimDarkMediumContrast = Color(0xFF131314)
val surfaceBrightDarkMediumContrast = Color(0xFF3A393A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0E0E0F)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1C1B1C)
val surfaceContainerDarkMediumContrast = Color(0xFF201F20)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2A2A2B)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF353435)

val primaryDarkHighContrast = Color(0xFFFFFFFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFA5E835)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFAFAFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA5CEFF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFFAF8)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFBE76)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF151925)
val onBackgroundDarkHighContrast = Color(0xFFF5F5F5)
val surfaceDarkHighContrast = Color(0xFF131314)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF444748)
val onSurfaceVariantDarkHighContrast = Color(0xFFF9FBFC)
val outlineDarkHighContrast = Color(0xFFC8CBCC)
val outlineVariantDarkHighContrast = Color(0xFFC8CBCC)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE5E2E3)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF1D2F00)
val surfaceDimDarkHighContrast = Color(0xFF131314)
val surfaceBrightDarkHighContrast = Color(0xFF3A393A)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0E0E0F)
val surfaceContainerLowDarkHighContrast = Color(0xFF1C1B1C)
val surfaceContainerDarkHighContrast = Color(0xFF201F20)
val surfaceContainerHighDarkHighContrast = Color(0xFF2A2A2B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF353435)

val quaternaryLight = Color(0xFFA900A8)
val onQuaternaryLight = Color(0xFFFFFFFF)
val quaternaryContainerLight = Color(0xFFFF60F7)
val onQuaternaryContainerLight = Color(0xFF310030)

val quaternaryLightMediumContrast = Color(0xFF7A007A)
val onQuaternaryLightMediumContrast = Color(0xFFFFFFFF)
val quaternaryContainerLightMediumContrast = Color(0xFFCE00CD)
val onQuaternaryContainerLightMediumContrast = Color(0xFFFFFFFF)

val quaternaryLightHighContrast = Color(0xFF430043)
val onQuaternaryLightHighContrast = Color(0xFFFFFFFF)
val quaternaryContainerLightHighContrast = Color(0xFF7A007A)
val onQuaternaryContainerLightHighContrast = Color(0xFFFFFFFF)

val quaternaryDark = Color(0xFFFFABF3)
val onQuaternaryDark = Color(0xFF5B005B)
val quaternaryContainerDark = Color(0xFFF732F4)
val onQuaternaryContainerDark = Color(0xFF000000)

val quaternaryDarkMediumContrast = Color(0xFFFFB2F3)
val onQuaternaryDarkMediumContrast = Color(0xFF2F002F)
val quaternaryContainerDarkMediumContrast = Color(0xFFF732F4)
val onQuaternaryContainerDarkMediumContrast = Color(0xFF000000)

val quaternaryDarkHighContrast = Color(0xFFFFF9FA)
val onQuaternaryDarkHighContrast = Color(0xFF000000)
val quaternaryContainerDarkHighContrast = Color(0xFFFFB2F3)
val onQuaternaryContainerDarkHighContrast = Color(0xFF000000)
